<!DOCTYPE html>
<html>

<head>
	<title>Registro de Empresa</title>
</head>

<body>

	<h1>Creacion de Empresa</h1>


	
		<form action="index.php?c=empresa&addEmpresa=1" method="post">
		NIF: <input type="number" name="nif" required> <br><br>
		Nombre: <input type="text" name="nombre" required><br><br>
		Direccion: <input type="text" name="direccion" required><br><br>
		Telefono: <input type="number" name="telefono" required> <br><br>
		Correo: <input type="email" name="correo" required><br><br>
		<input type="submit" value="Crear">
        </form>

	



</body>
 
</html>