<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <?php
    if (isset($_SESSION['info'])) {
        echo "<script>alert('" . $_SESSION['info'] . "')</script>";

        unset($_SESSION['info']); // elimina la variable de sesión
    }
    ?>
    <h1>Inicia sesión</h1>
    <form action="index.php?c=user" method="post">
        <input type="text" id="name" name="username" required placeholder="nombre usuario"><br><br>
        <input type="password" id="password" name="password" placeholder="contraseña" required><br>

        <input type="submit" value="Submit">
    </form>
    <p>¿No tienes cuenta? <a href="index.php?c=user&a=register">Regístrate</a></p>
    <?php


    ?>
</body>

</html>