<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Modificar Objeto</title>
</head>
<body>
    <h1>Modificar Objeto</h1>
    <form action="index.php?c=admin&edit=1&id=<?php echo $id; ?>" method="POST">
        <div>
            <label for="descripcion">Descripción:</label>
            <input type="text" id="descripcion" name="descripcion" required>
        </div>
        <div>
            <label for="cantidad">Cantidad:</label>
            <input type="number" id="cantidad" name="cantidad" min="1" required>
        </div>
        <div>
            <label for="ubicacion">Pasillo:</label>
            <input type="text" id="ubicacion" name="pasillo" required>
        </div>
        <div>
            <label for="ubicacion">Estanteria:</label>
            <input type="text" id="ubicacion" name="estanteria" required>
        </div>
        <div>
            <label for="ubicacion">Estante:</label>
            <input type="text" id="ubicacion" name="estante" required>
        </div>
        <div>
            <button type="submit">Modificar Objeto</button>
        </div>
    </form>
</body>
</html>
