<h1>Pagina principal</h1>
<a href="index.php?c=register&registerView=1">Register</a>
<a href="index.php?c=login&loginView=1">Login</a>
<br><br><br><br>
<?php
if (isset($_SESSION["user"])) {
    $user = $_SESSION["user"];
    if ($user->esAdmin()) {
        echo "<h3>Perteneces a la sección de administradores.</h3>";
        echo "<a href='index.php?c=admin&adminView=1'>Panel de administradores</a>";
    }
    echo "<br><br><br>";
    echo "Hola " . $user->getNombre();
    if ($user->getNombre() !== 'invitado') {
        echo " <a href='index.php?c=login&logout=1'>Salir</a><br><br>";
    }
} else {
    echo "Bienvenido, invitado. Por favor, inicia sesión.";
}

?>