<html>
<form method='post' action='index.php?c=tienda' enctype='multipart/form-data'>
            <input type='text' name='nombre' placeholder='Nombre del producto'>
            <input type='text' name='descripcion' placeholder='Descripcion del producto'>
            <input type='file' name='imagen' placeholder='imagen del producto'>
            <input type='number' name='precio' placeholder='Precio del producto'>
            <input type='number' name='cantidad' placeholder='Cantidad del producto'>
            <input type='submit' value='Añadir'>
        </form>
</html>