<html>
    <h1>Esta es la pagina para los administradores</h1>


    <p>Estas son las funciones disponibles para administradores:</p>
    <ul>
        <li><a href="index.php?c=tienda&productView=1">Gestionar productos</a></li>
        <li><a href="index.php?c=tienda&usersView=1">Gestionar usuarios</a></li>
    </ul>
    <a href="index.php?c=tienda&mainView=1">Volver a la pagina principal</a>
</html>