<h1>Panel de administradores</h1> 

<a href="index.php?c=admin&change=1&list=1">Cambiar rol a usuarios</a><br><br> 
<a href="index.php?c=admin&delete=1">Ver todos los registros</a>



<?php 
    if(isset($_GET['change'])){ 
        $users = UserRepository::getusers();
         foreach($users as $user){ 
            echo "- ".$user->getUsername()." <a href='index.php?c=admin&changeRole=1&id=".$user->getId()."'>X
            </a>". " <a href='index.php?c=admin&newRole=1&id=".$user->getId()."'>✔</a>". "<br>";
        }
    }

?> <br><br>

<a href="index.php">Volver</a>
