<html>

<h1>Pagina de profesores:</h1>

<a href="index.php?c=profesor&newEmpresa=1">Dar de alta una empresa</a><br>
<a href="index.php?c=profesor&editEmpresa=1">Editar una empresa</a><br>
<a href="index.php?c=profesor&deleteEmpresa=1">Listado y eliminacion de empresas</a><br>
<a href="index.php?c=profesor&listadoAlumnos=1">Listado de alumnos</a><br>
<a href="index.php?c=profesor&listadoProfesores=1">Listado de profesores</a><br>
<a href="index.php?c=profesor&asignar=1">Asignar alumno a empresa</a><br>
<a href="index.php?c=profesor&editAsignacion=1">Editar lista de practicas</a>



  


<br><br>
<a href="index.php">Volver</a>
</html>