
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>REGISTER</title>
</head>
<body>
    <h1>Register</h1>
    <form action="index.php?c=register" method="post" >
        <input type="text" name="username" placeholder="nombre usuario">
        <input type="password" name="password" placeholder="contraseña">
        <br><br>
        <input type="submit" value="register" name="register">
    </form>
</body>
</html>